Models/EFModel/GuestBook.cs
namespace WebAppMVC.Models.EFModel
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class GuestBook
    {
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public int Id { get; set; }

        [Required]
        [StringLength(50)]
        public string Name { get; set; }

        [Required]
        [StringLength(50)]
        public string Email { get; set; }

        [StringLength(10)]
        public string CellPhone { get; set; }

        [Required]
        [StringLength(50)]
        public string Message { get; set; }

        public DateTime CreateTIme { get; set; }
    }
}

Models/EFModel/Register.cs
namespace WebAppMVC.Models.EFModel
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class Register
    {
        public int Id { get; set; }

        [Required]
        [StringLength(50)]
        public string Name { get; set; }

        [Required]
        [StringLength(200)]
        public string Email { get; set; }

        public DateTime CreateTime { get; set; }
    }
}

Models/EFModel/RegisterModel.cs
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;
using System.Linq;

namespace WebAppMVC.Models.EFModel
{
    public partial class RegisterModel : DbContext
    {
        public RegisterModel()
            : base("name=RegisterModel")
        {
        }

        public virtual DbSet<GuestBook> GuestBooks { get; set; }
        public virtual DbSet<Register> Registers { get; set; }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            modelBuilder.Entity<GuestBook>()
                .Property(e => e.CellPhone)
                .IsUnicode(false);
        }
    }
}

Models/Service/RegisterService.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

using WebAppMVC.Data;
using WebAppMVC.Models.EFModel;

namespace WebAppMVC.Models.Service
{
    public class RegisterService
    {
        private WebAppMVCContext db = new WebAppMVCContext();
        public void Create(Register register)
        {
            var data = db.Registers.FirstOrDefault(x => x.Email == register.Email);
            if (data != null)
            {
                throw new Exception("這個email已經報名過了");
            }

            #region
            register.CreateTime = DateTime.Now;
            #endregion
            db.Registers.Add(register);
            db.SaveChanges();
        }
        public Register Find(int id)
        {
            Register register = db.Registers.Find(id);
            if (register == null)
            {
                throw new Exception("record not found");
            }
            return register;
        }


    }
}

Models/ViewModel/RegisterVM.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

using WebAppMVC.Models.EFModel;

namespace WebAppMVC.Models.ViewModel
{
    public class RegisterVM
    {
        [Required]
        [StringLength(50)]
        public string Name { get; set; }

        [Required]
        [StringLength(200)]
        public string Email { get; set; }

    }
    public class RegisterDetailsVM
    {
        public int Id { get; set; }

        [Required]
        [StringLength(50)]
        public string Name { get; set; }

        [Required]
        [StringLength(200)]
        public string Email { get; set; }

        public DateTime CreateTime { get; set; }
    }

    public  static class RegisterAssember
    {
        public static Register VM2Entity(this RegisterVM source)
        {
            return new Register {Name= source.Name, Email=source.Email};
        }
        public static RegisterDetailsVM Entity2DetailsVM(this Register source)
        {
            return new RegisterDetailsVM {Id=source.Id,
                Name = source.Name,
                Email = source.Email,
                CreateTime=source.CreateTime
            };
        }
        public static List<RegisterDetailsVM> Entity2DetailsVM(this IEnumerable<Register> source)
        {
            if (source == null || source.Count() == 0)
            {
                return Enumerable.Empty<RegisterDetailsVM>().ToList();
            }
            return source.Select(x=>x.Entity2DetailsVM()).ToList();
        }

    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebAppMVC.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Controllers/RegistersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebAppMVC.Data;
using WebAppMVC.Models.EFModel;
using WebAppMVC.Models.Service;
using WebAppMVC.Models.ViewModel;

namespace WebAppMVC.Controllers
{
    public class RegistersController : Controller
    {
        private WebAppMVCContext db = new WebAppMVCContext();

        // GET: Registers
        public ActionResult Index()
        {
            return View();
        }

        // GET: Registers/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }


            try
            {
               Register register = new RegisterService().Find(id.Value);
                return View(register.Entity2DetailsVM());
            }
            catch (Exception)
            {

               return HttpNotFound();
            }


            //if (id == null)
            //{
            //    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            //}
            //Register register = db.Registers.Find(id);
            //if (register == null)
            //{
            //    return HttpNotFound();
            //}
           
        }

        // GET: Registers/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Registers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(RegisterVM register)
        {
            try
            {
        
                //var data = db.Registers.FirstOrDefault(x => x.Email == register.Email);
                //if (data != null)
                //{
                //   throw new Exception("這個email已經報名過了");
                //}

                //#endregion
                //#region
                //register.CreateTime = DateTime.Now;
                //#endregion
                //db.Registers.Add(register);
                //db.SaveChanges();
                new RegisterService().Create(register.VM2Entity());
            }
            catch (Exception)
            {

                ModelState.AddModelError(string.Empty, "這個Email 已經報名過了 無法在報名");
            }




         



            if (ModelState.IsValid)
            {
                return RedirectToAction("Index");
            }

            return View(register);
        }




        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Registers/Create.cshtml
@model WebAppMVC.Models.ViewModel.RegisterVM

@{
    ViewBag.Title = "Create";
}

<h2>報名研討會</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>註冊</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })

            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

@*<div>
    @Html.ActionLink("Back to List", "Index")
</div>*@

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Registers/Details.cshtml
@model WebAppMVC.Models.ViewModel.RegisterDetailsVM

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Register</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreateTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreateTime)
        </dd>

    </dl>
</div>
@*<p>
    @Html.ActionLink("Back to List", "Index")
</p>*@

Views/Registers/Edit.cshtml
@model WebAppMVC.Models.EFModel.Register

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Register</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CreateTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreateTime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CreateTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Registers/Index.cshtml
@model IEnumerable<WebAppMVC.Models.ViewModel.RegisterDetailsVM>

@{
    ViewBag.Title = "Index";
}

<h2>網站註冊報名網站</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CreateTime)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CreateTime)
        </td>
        <td>
            @Html.ActionLink("明細", "Details", new { id=item.Id })
        </td>
    </tr>
}

</table>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("研討會報名網站", "Index", "Registers", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("回首頁", "Index", "Registers")</li>
                    <li>@Html.ActionLink("報名研討會", "Create", "Registers")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>